import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { ShopContextProvider } from "@/context/shopContext";
import { FilterContextProvider } from "@/context/filterContext";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container overflow-x-hidden">
        <FilterContextProvider>
          <ShopContextProvider>
            <Header />
            {children}
            <Toaster />
            <Footer />
          </ShopContextProvider>
        </FilterContextProvider>
      </body>
    </html>
  );
}
